import type { Metadata } from "next";
import { site } from "@/content/site";

type OpenGraph = NonNullable<Metadata["openGraph"]>;

/** Title used on the home page and as the fallback for any route without one. */
export const siteTitle = `${site.name} — ${site.fullName}`;

/**
 * Link-preview card, generated by `npm run generate:brand`. It is served from
 * public/ rather than as a file-based `opengraph-image`, because Next.js drops
 * a file-based image on any page that sets its own `openGraph` — which is every
 * page here.
 */
export const previewImage = {
  url: "/opengraph-image.png",
  width: 1200,
  height: 630,
  alt: `${site.fullName} (${site.name}), ${site.department}, ${site.university}`,
};

/**
 * Open Graph fields every route shares. Next.js merges metadata shallowly, so a
 * page that sets its own `openGraph` replaces the layout's object wholesale —
 * these have to be spread back in rather than inherited.
 */
export const sharedOpenGraph = {
  type: "website",
  siteName: site.name,
  locale: "en_US",
  images: [previewImage],
} satisfies OpenGraph;

/**
 * Canonical URL and link-preview fields for one page. Every page declares its
 * own; setting them in the root layout instead would make each subpage claim
 * to be the home page.
 */
export function pageMetadata({
  title,
  description,
  path,
}: {
  /** Omit on the home page, which uses `siteTitle` unchanged. */
  title?: string;
  description: string;
  /** Route path with a trailing slash, to match `trailingSlash: true`. */
  path: string;
}): Metadata {
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: {
      ...sharedOpenGraph,
      title: title ? `${title} — ${site.name}` : siteTitle,
      description,
      url: path,
    },
  };
}
